using System.Globalization;
using System.Reflection;
using BiscuitSharp;

if (args.Length == 3 && args[0] == "--verify-symbols")
{
    using var zip = System.IO.Compression.ZipFile.OpenRead(args[1]);
    var pdbs = zip.Entries.Where(e => e.FullName.EndsWith(".pdb", StringComparison.Ordinal)).ToArray();
    if (pdbs.Length != 2) throw new InvalidOperationException("Expected symbols for both target frameworks");
    foreach (var pdb in pdbs)
    {
        using var stream = pdb.Open();
        using var buffer = new MemoryStream();
        stream.CopyTo(buffer);
        buffer.Position = 0;
        using var provider = System.Reflection.Metadata.MetadataReaderProvider.FromPortablePdbStream(buffer);
        var reader = provider.GetMetadataReader();
        bool found = false;
        foreach (var handle in reader.CustomDebugInformation)
        {
            var item = reader.GetCustomDebugInformation(handle);
            if (reader.GetGuid(item.Kind) != Guid.Parse("CC110556-A091-4D38-9FEC-25AB9A351A6A")) continue;
            using var json = System.Text.Json.JsonDocument.Parse(reader.GetBlobBytes(item.Value));
            var mappings = json.RootElement.GetProperty("documents").EnumerateObject().ToArray();
            string prefix = "https://raw.githubusercontent.com/jenolaszlo-sketch/biscuit-sharp/" + args[2] + "/";
            if (mappings.Length == 0 || mappings.Any(m => m.Value.GetString()?.StartsWith(prefix, StringComparison.Ordinal) != true))
                throw new InvalidOperationException("SourceLink mapping does not bind to the qualified repository SHA");
            found = true;
        }
        if (!found) throw new InvalidOperationException("Missing SourceLink in " + pdb.FullName);
        Console.WriteLine("Verified SourceLink: " + pdb.FullName);
    }
    return;
}

if (args.Length != 2 || args[0] is not ("--write" or "--verify"))
    throw new ArgumentException("Usage: --write|--verify <inventory-path>");

var nullability = new NullabilityInfoContext();
var lines = new List<string>();
foreach (Type type in typeof(BiscuitToken).Assembly.GetExportedTypes().OrderBy(t => t.FullName, StringComparer.Ordinal))
{
    string parents = string.Join(", ", new[] { type.BaseType }.Where(t => t is not null).Cast<Type>()
        .Concat(type.GetInterfaces()).Select(t => Name(t)).Order(StringComparer.Ordinal));
    lines.Add($"type {Name(type)} [{(type.IsEnum ? "enum" : type.IsValueType ? "struct" : "class")}; abstract={type.IsAbstract}; sealed={type.IsSealed}] : {parents}");
    foreach (MemberInfo member in type.GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
        .OrderBy(m => m.Name, StringComparer.Ordinal).ThenBy(m => m.ToString(), StringComparer.Ordinal))
    {
        string? signature = member switch
        {
            ConstructorInfo c => $"ctor({Parameters(c)})",
            MethodInfo m when !m.IsSpecialName => $"{Modifiers(m)}{Name(m.ReturnType, nullability.Create(m.ReturnParameter))} {m.Name}{Generic(m)}({Parameters(m)})",
            PropertyInfo p => $"{(p.GetMethod?.IsStatic == true || p.SetMethod?.IsStatic == true ? "static " : "")}{Name(p.PropertyType, nullability.Create(p))} {p.Name}{(p.GetIndexParameters().Length == 0 ? "" : $"[{string.Join(", ", p.GetIndexParameters().Select(Parameter))}]")} {{ {(p.GetMethod?.IsPublic == true ? "get; " : "")}{(p.SetMethod?.IsPublic == true ? (p.SetMethod.ReturnParameter.GetRequiredCustomModifiers().Any(t => t.FullName == "System.Runtime.CompilerServices.IsExternalInit") ? "init; " : "set; ") : "")}}}",
            FieldInfo f => $"{(f.IsStatic ? "static " : "")}{(f.IsInitOnly ? "readonly " : "")}{Name(f.FieldType, nullability.Create(f))} {f.Name}{(f.IsLiteral ? " = " + Value(f.GetRawConstantValue()) : "")}",
            EventInfo e => $"event {Name(e.EventHandlerType!)} {e.Name}",
            _ => null
        };
        if (signature is not null)
        {
            lines.Add("  " + signature);
            foreach (CustomAttributeData attribute in member.GetCustomAttributesData()
                .Where(a => a.AttributeType.FullName is "System.ObsoleteAttribute"
                    or "System.Diagnostics.CodeAnalysis.RequiresUnreferencedCodeAttribute"
                    or "System.Diagnostics.CodeAnalysis.RequiresDynamicCodeAttribute"))
                lines.Add("    " + attribute);
        }
    }
}
string inventory = "# BiscuitSharp public API; generated by BiscuitSharp.ApiSurface. Review changes before accepting.\n"
    + string.Join("\n", lines) + "\n";
string path = Path.GetFullPath(args[1]);
if (args[0] == "--write")
{
    File.WriteAllText(path, inventory);
    Console.WriteLine($"Wrote {lines.Count} API entries to {path}");
}
else if (!File.Exists(path) || File.ReadAllText(path).Replace("\r\n", "\n") != inventory)
    throw new InvalidOperationException("Public API differs from the reviewed inventory. Regenerate and review docs/public-api.txt.");
else
    Console.WriteLine($"Public API matches ({lines.Count} entries).");

string Name(Type type, NullabilityInfo? info = null)
{
    if (type.IsByRef) return Name(type.GetElementType()!, info) + "&";
    if (type.IsArray) return Name(type.GetElementType()!, info?.ElementType) + "[" + new string(',', type.GetArrayRank() - 1) + "]" + Nullable(type, info);
    string name = type.IsGenericParameter ? type.Name : (type.FullName ?? type.Name);
    if (type.IsGenericType)
    {
        name = name[..name.IndexOf('`')];
        name += "<" + string.Join(", ", type.GetGenericArguments().Select((t, i) => Name(t, info?.GenericTypeArguments.ElementAtOrDefault(i)))) + ">";
    }
    return name + Nullable(type, info);
}
static string Nullable(Type type, NullabilityInfo? info) =>
    !type.IsValueType && info?.ReadState == NullabilityState.Nullable ? "?" : "";
string Parameters(MethodBase method) => string.Join(", ", method.GetParameters().Select(Parameter));
string Parameter(ParameterInfo p) =>
    (p.IsOut ? "out " : p.ParameterType.IsByRef ? "ref " : p.GetCustomAttribute<ParamArrayAttribute>() is not null ? "params " : "")
    + Name(p.ParameterType.IsByRef ? p.ParameterType.GetElementType()! : p.ParameterType, nullability.Create(p))
    + " " + p.Name + (p.HasDefaultValue ? " = " + Value(p.DefaultValue) : "");
static string Value(object? value) => value is null ? "null"
    : value is string text ? System.Text.Json.JsonSerializer.Serialize(text)
    : Convert.ToString(value, CultureInfo.InvariantCulture) ?? "null";
static string Modifiers(MethodInfo method) =>
    (method.IsStatic ? "static " : "") + (method.IsAbstract ? "abstract " : method.IsVirtual && !method.IsFinal ? "virtual " : "");
string Generic(MethodInfo method) => !method.IsGenericMethod ? "" : "<" + string.Join(", ",
    method.GetGenericArguments().Select(t => t.Name + "[" + t.GenericParameterAttributes + "; "
    + string.Join(", ", t.GetGenericParameterConstraints().Select(c => Name(c))) + "]")) + ">";
